apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sample-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
